### ISSUE TITLE
error on windows

### ISSUE THREAD

**Issue by seanwessmith** [lostVkng/smodels#2]
Change line 6 to import decimals.js with a lowercase d.
this was causing an error on windows/linux and older versions of Node.js

before:
const Decimal = require('Decimal.js')

after:
const Decimal = require('decimal.js')

**Comment by lostVkng** [comment]
I fixed this, it was just the one js file. Good catch!

**Comment by seanwessmith** [comment]
Excellent, thanks for the fix. Could you also redeploy the NPM module?
